visualstock/backup/urls.py
from django.urls import path

from . import views

app_name="backup"
urlpatterns = [
    path("<str:stock_name>/<int:backup_num>", views.toggle_backup, name="toggle_backup"),
]

visualstock/mainapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("stock/", views.index, name="index"),
    path("stock/add", views.addStock, name="addStock"),
    path("stock/edit", views.editStock, name="editStock"),
    path("stock/delete", views.deleteStock, name="deleteStock"),
    path("", views.index, name="index"),
    path("stock/<str:stock_name>/export", views.stock_to_csv, name="stock_to_csv"),
]

visualstock/stock/urls.py
from django.urls import path

from . import views

app_name="stock"
urlpatterns = [
    path("<str:stock_name>/", views.stock, name="stock"),
    path("<str:stock_name>/edit", views.editProducts, name="editProducts"),
    path("<str:stock_name>/import_images", views.importProductImages, name="importProductImages"),
    path("<str:stock_name>/delete", views.deleteProducts, name="deleteProducts"),
]

visualstock/visualstock/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings

from django.views.static import serve 

urlpatterns = [
    path('stock/', include('stock.urls')),
    path('backup/', include('backup.urls')),
    path('', include('mainapp.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

#Configuración para cargar imagenes.
#En modo de desarrollo, es decir, en local.
if settings.DEBUG:
    from django.conf.urls.static import static
    #cargamos los archivos estaticos para que puedan ser leidos.
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visualstock/mainapp/models.py
from django.db import models

visualstock/mainapp/views.py
import csv

from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import JsonResponse, HttpResponse
from django.core.exceptions import ValidationError

from stock.models import Stock
from stock.forms import AddStockStepOne, AddStockStepTwo, AddStockOptional, DeleteStock, EditFaceStock
from .addStock_implement import validate_stock

from django.contrib.auth.hashers import check_password

from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone

# Create your views here.
def index(request):
    """
        Render the index both before logging and after.
    """
    
    context = {
    'title' : 'Inicio',
    'is_index' : True,
    'mode' : 0
    }

    if request.user.is_authenticated:
        context["stocks"] = Stock.objects.filter(user__pk=request.user.pk)
        context["stock_step_one"] = AddStockStepOne()
        context["stock_step_two"] = AddStockStepTwo()
        context["stock_optional"] = AddStockOptional()
        context["delete_stock"] = DeleteStock(auto_id=False)
        context["edit_stock"] = EditFaceStock(auto_id=False)

        if request.GET.get("mode"):
            context["mode"] = int(request.GET.get("mode"))

    return render(request, 'mainapp/index.html', context)

@login_required
def addStock(request) -> JsonResponse:
    """
        Validate and add a stock.
    """
    if request.method == 'POST' and request.user.username != "Invitados":
        data = validate_stock(request)
        return JsonResponse(data)

@login_required
def editStock(request):
    """
        Edit the cover of the stock, either its name or its image.
    """
    if request.method == 'POST' and request.user.username != "Invitados":
        edit_stock = EditFaceStock(request.POST, request.FILES)
        if edit_stock.is_valid():
            stock_id = request.POST.get("stock_id")
            stock_to_edit = get_object_or_404(Stock, id=stock_id)
            previous_name = stock_to_edit.name
            name = request.POST.get("name")
            image = request.FILES.get("image")
            update_fields = []
            if name:
                stock_to_edit.name = name
                update_fields.append('name')
            if image:
                stock_to_edit.image = request.FILES.get("image")
                update_fields.append('image')
            try:
                stock_to_edit.save(update_fields=update_fields)
                messages.success(request, f"Editado correctamente: {previous_name} ===> {stock_to_edit.name}")
            except ValidationError as e:
                messages.error(request, e.message)
        else:
            messages.error(request, "Edición incorrecta, vuelva a intentarlo.")
        index_edit_mode = reverse('index')+'?mode=1'
        return redirect(index_edit_mode)


@login_required
def deleteStock(request):
    """
        Delete the stock validating it with the user password.
    """
    if request.method == 'POST' and request.user.username != "Invitados":
        delete_stock = DeleteStock(request.POST)
        if delete_stock.is_valid():
            password = request.POST.get("password")
            if check_password(password, request.user.password):
                stock_id = request.POST.get("stock_id")
                stock_to_remove = get_object_or_404(Stock, id=stock_id)
                stock_name = stock_to_remove.name
                stock_to_remove.delete()
                messages.warning(request, f"Stock {stock_name} eliminado correctamente!")
            else:
                messages.error(request, "Contraseña incorrecta!")

        index_delete_mode = reverse('index')+'?mode=2'
        return redirect(index_delete_mode)

@login_required
def stock_to_csv(request, stock_name) -> HttpResponse:
    """
        Exports the csv file corresponding to the current state of the stock.
    """
    stocks = Stock.objects.filter(user__pk=request.user.pk)
    stock_by_name = get_object_or_404(stocks, name=stock_name)
    category = bool(stock_by_name.category_column)*stock_by_name.category_column+(not bool(stock_by_name.category_column))*"Categoria"

    response = HttpResponse(
        content_type='text/csv',
        headers={'Content-Disposition': f'attachment; filename="{stock_name}-{timezone.now().date()}.csv"'},
    )

    writer = csv.writer(response)

    titles =  [stock_by_name.name_column, 
                    stock_by_name.price_column, 
                    stock_by_name.quantity_column, 
                    "Disponible", 
                    category,
                    stock_by_name.added_date_column, 
                    stock_by_name.updated_date_column] + stock_by_name.additional_column_as_list()

    writer.writerow(titles)
    products = stock_by_name.products.all()
    for product in products:
        avaliable = product.available*"✓"+(not product.available)*"X"
        writer.writerow(
                        [product.name, 
                        product.price, 
                        product.quantity, 
                        avaliable, 
                        product.category, 
                        product.added_date, 
                        product.updated_date] + product.additional_as_list()
                        )

    return response

visualstock/mainapp/templates/mainapp/index.html
{% extends 'layouts/layout.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock title %}

{% block content %}
    {% if request.user.is_authenticated %}
        {% include 'mainapp/index_state/index_authenticated.html' %}
    {% else %}
        {% include 'mainapp/index_state/index_not_authenticated.html' %}
    {% endif %}
{% endblock content %}

{% block scripts %}
    {% if request.user.is_authenticated %}
    <script>const url_add_stock = "{% url 'addStock' %}";</script>
    <script src="{% static '/js/addStockInteractive.js'%}" async></script>
        {% if mode == 1 %}
            <script src="{% static 'js/displayEditStock.js' %}" async></script>
        {% endif %}
        {% if mode == 2 %}
            <script src="{% static 'js/displayDeleteStock.js' %}" async></script>
        {% endif %}
    {% endif %}
{% endblock scripts %}

visualstock/mainapp/templates/mainapp/modal_addStock.html
<label for="addStockCheck">
    <div class="close_panel"></div>
</label>
<div class="plain_panel">
    <label for="addStockCheck">
        <div class="button__model modal__close-button"><div class="button__color-layer"></div><span class="button__text icon-close"></span><span class="button__hide-icon icon-close"></span></div>
    </label>
    <button class="" onclick=""></button>
    <div class="errors-content collapse">
        <ul class="ul__stock-add--errors"></ul>
    </div>
    <h2 class="section__title">Añadir Stock</h2>
    <div class="section__description">
        <div class="form__addStock-content">

            <form id="form__stock-add" action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form__first_step">
                    {% for field in stock_step_one %}
                        <label for="{{ field.auto_id }}">
                            {{ field.label }}
                        </label>
                        {{ field }}
                        {% if field.field.widget.input_type == 'file' %}
                            <div class="upload-file__interfaz">
                                <label for="{{ field.auto_id }}" class="upload-file__button-load" tabindex="{{ forloop.counter }}"><span class="upload-file__button-icon icon-upload"></span class="upload-file__button-text"><span>Subir Archivo</span></label>
                                <span class="upload-file__filename"></span>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
                <div class="form__second_step collapse">
                    {% for field in stock_step_two %}
                        <label for="{{ field.auto_id }}">{{ field.label }}</label>
                        {{ field }}
                    {% endfor %}
                </div>
                <datalist id="columnoptions"></datalist>
            </form>
        
            <button class="button__model" type="button" form="form__stock-add" formenctype="multipart/form-data" onclick="ProcesarDatos()"><div class="button__color-layer"></div><span class="button__text">Subir Stock</span><span class="button__hide-icon icon-upload"></span></button>
        </div>
    </div>
</div>

visualstock/mainapp/templates/mainapp/navbar.html
<div class="burger-button--content">
    <button class="icon-menu3"></button>
</div>
    
<nav class="{% if request.user.is_authenticated %}nav__post-login{% endif %}"">
    <ul>
    {% if not is_index %}
        <li class="li__index {% if not request.user.is_authenticated %} li__x--large {% endif %}">
            <a href="{% url 'index' %}" tabindex="3">
                <span class="icon-home3"></span>
                <span class="menu--principal-text">
                    Inicio
                </span>
            </a>
        </li>
    {% endif %}
    {% if request.user.is_authenticated %}
        <li class="li__created-stocks" tabindex="3">
            <span class="menu--principal-text">
                Stocks Creados
            </span>
            <div class="submenu__triangle-draw"></div>
            <ul class="ul__stocks">
                {% for stock in stocks %}
                    <li class="li__stock">
                        <a tabindex="3" href="{% url 'stock:stock' stock.name %}">{{ stock.name }}</a>
                    </li>
                {% empty %}
                    <li class="li__backup">
                        Sin stocks por el momento
                    </li>
                {% endfor %}
            </ul>
        </li>
        {% if is_stock %}
            <li class="li__modes-stocks" tabindex="3">
                <span class="menu--principal-text">
                    Modos
                </span>
                <div class="submenu__triangle-draw"></div>
                <ul class="ul__modes">
                    {% if not mode == 1 %}
                        <li class="li__mode" title="Para editar productos">
                            <a tabindex="3" href="{% url 'stock:stock' stock.name %}?mode=1">Edición</a>
                        </li>
                    {% endif %}
                    {% if not mode == 2 %}
                        <li class="li__mode" title="Para eliminar productos">
                            <a tabindex="3" href="{% url 'stock:stock' stock.name %}?mode=2"><span class="icon-bin"></span>&nbsp;Eliminación</a>
                        </li>
                    {% endif %}
                    {% if not mode == 0 %}
                        <li class="li__mode" title="Para visualizar productos">
                            <a tabindex="3" href="{% url 'stock:stock' stock.name %}">Visualización</a>
                        </li>
                    {% endif %}
                </ul>
            </li>
            <li class="li__backup-stocks" tabindex="3">
                <span class="menu--principal-text">
                    Respaldos
                </span>
                <div class="submenu__triangle-draw"></div>
                <ul class="ul__backups">
                    {% if not stock.backup.third_date %}
                        <li class="li__backup">
                            Sin respaldos por el momento
                        </li>
                    {% endif %}
                    {% if stock.backup.first_date %}
                        <li class="li__backup">
                            <a tabindex="3" 
                            href=
                            {% if request.user.username == "Invitados" %}
                                ""
                            {% else %}
                                "{% url 'backup:toggle_backup' stock.name 1 %}"
                            {% endif %}
                                >
                                <span class="icon-history"></span>&nbsp;{{ stock.backup.first_date}} - [Más antiguo]
                            </a>
                        </li>
                    {% endif %}
                    {% if stock.backup.second_date %}
                        <li class="li__backup">
                            <a tabindex="3"
                            href=
                            {% if request.user.username == "Invitados" %}
                                ""
                            {% else %}
                                "{% url 'backup:toggle_backup' stock.name 2 %}"
                            {% endif %}
                                >
                                <span class="icon-history"></span>&nbsp;{{ stock.backup.second_date }} - [Antiguo]
                            </a>
                        </li>
                    {% endif %}
                    {% if stock.backup.third_date %}
                        <li class="li__backup">
                            <a tabindex="3"
                                href=
                                {% if request.user.username == "Invitados" %}
                                    ""
                                {% else %}
                                    "{% url 'backup:toggle_backup' stock.name 3 %}"
                                {% endif %}
                                    >
                                <span class="icon-history"></span>&nbsp;{{ stock.backup.third_date}} - [Reciente]
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </li>
        {%  endif %}
        {% if is_index %}
            <li class="li__modes-stocks" tabindex="3">
                <span class="menu--principal-text">
                    Modos
                </span>
                <div class="submenu__triangle-draw"></div>
                <ul class="ul__modes">
                    {% if not mode == 1 %}
                        <li class="li__mode" title="Para editar Stocks">
                            <a tabindex="3" href="{% url 'index'%}?mode=1">Edición</a>
                        </li>
                    {% endif %}
                    {% if not mode == 2 %}
                        <li class="li__mode" title="Para eliminar Stocks">
                            <a tabindex="3" href="{% url 'index'%}?mode=2"><span class="icon-bin"></span>&nbsp;Eliminación</a>
                        </li>
                    {% endif %}
                    {% if not mode == 0 %}
                        <li class="li__mode" title="Para visualizar Stocks">
                            <a tabindex="3" href="{% url 'index'%}">Visualización</a>
                        </li>
                    {% endif %}
                </ul>
            </li>
            <li class="li__backup-stocks" tabindex="3">
                <span class="menu--principal-text">
                    Descargar Original
                </span>                    
                    <div class="submenu__triangle-draw"></div>
                    <ul class="ul__backups">
                        {% for stock in stocks %}
                            <li class="li__backup">
                                <a tabindex="3" href="{{ stock.principal_file.url }}" download><span class="icon-floppy-disk"></span>&nbsp;{{ stock.name }}</a>
                            </li>
                        {% empty %}
                            <li class="li__backup">
                                Sin stocks por el momento
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="li__backup-stocks" tabindex="3">
                    <span class="menu--principal-text">
                        Exportar .csv
                    </span>
                    <div class="submenu__triangle-draw"></div>
                    <ul class="ul__backups">
                        {% for stock in stocks %}
                            <li class="li__backup">
                                <a tabindex="3" href="{% url 'stock_to_csv' stock.name %}" download><span class="icon-download"></span>&nbsp;{{ stock.name }}</a>
                            </li>
                        {% empty %}
                            <li class="li__backup">
                                Sin stocks por el momento
                            </li>
                        {% endfor %}
                    </ul>
                </li>

        {% endif %}
        <li class="li__user-button" tabindex="3">
           <span class="icon-user"></span>&nbsp;{{ user.username }}
           <div class="submenu__triangle-draw"></div>
           <ul class="ul__user-options">
                <li class="li__user-option li__logout-option">
                    <a tabindex="3" href="{% url 'logout' %}?next={% url 'index' %}">Cerrar Sesión</a>
                </li>
           </ul>
        </li>
    {% else %}
        <li class="li__x--large">
            <a href="{% url 'signup' %}" tabindex="3">Registrarse</a>
        </li>
        <li class="li__x--large">
            <a href="{% url 'login' %}" tabindex="3">Iniciar Sesión</a>
        </li>
    {% endif %}
    </ul> 
</nav>
<div class="bg_navbar"></div>

visualstock/mainapp/templates/mainapp/popup_message.html
{% if messages %}
{% for message in messages %}
    <input type="checkbox" id="closePopUp">
    <div class="popup_message  
                    {% if message.level == 25 %} 
                        success_level
                    {% elif message.level == 20 %} 
                        info_level
                    {% elif message.level == 30 %} 
                        warning_level
                    {% elif message.level == 40 %} 
                        error_level
                    {% endif %}">
        {{ message | safe }}
        <label for="closePopUp">
            <span class="popup_close_button"></span>
        </label>
    </div>
{% endfor %}
{% endif %}