visualstock/stock/urls.py
from django.urls import path

from . import views

app_name="stock"
urlpatterns = [
    path("<str:stock_name>/", views.stock, name="stock"),
    path("<str:stock_name>/edit", views.editProducts, name="editProducts"),
    path("<str:stock_name>/import_images", views.importProductImages, name="importProductImages"),
    path("<str:stock_name>/delete", views.deleteProducts, name="deleteProducts"),
]

visualstock/visualstock/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings

from django.views.static import serve 

urlpatterns = [
    path('stock/', include('stock.urls')),
    path('backup/', include('backup.urls')),
    path('', include('mainapp.urls')),
    path('', include('users.urls')),
    path('admin/', admin.site.urls),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}), 
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
]

#Configuración para cargar imagenes.
#En modo de desarrollo, es decir, en local.
if settings.DEBUG:
    from django.conf.urls.static import static
    #cargamos los archivos estaticos para que puedan ser leidos.
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

visualstock/stock/models.py
import uuid

from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save, post_save, post_delete, pre_delete

from backup.models import Backup
from .get_products import get_and_save_products
from .receivers import (
                        delete_residual_files,
                        set_additional_column,
                        set_default_date_column_name,
                        unique_name_per_user,
                        delete_storage_files,
                        append_residual_files,
                        delete_residual_files,
                        delete_backup_files
                        )
from products.receivers import set_compressed_image

class Stock(models.Model):
    name = models.CharField(max_length=50, verbose_name="Nombre")
    image = models.ImageField(upload_to=f"Images/%Y/%m/%d/{uuid.uuid4().hex}/", max_length=100, verbose_name="Imagen")
    
    principal_file = models.FileField(upload_to=f"StockFiles/%Y/%m/%d/{uuid.uuid4().hex}/", verbose_name="Archivo fuente")
    
    name_column = models.CharField(max_length=50, verbose_name="Columna de nombre-producto")
    price_column = models.CharField(max_length=50, verbose_name="Columna precio")
    quantity_column = models.CharField(max_length=50, verbose_name="Columna cantidad")
    category_column = models.CharField(blank=True, default="", max_length=50, verbose_name="Columna categorias")
    added_date_column = models.CharField(blank=True, default="", max_length=50, verbose_name="Columna de fecha-añadido")
    updated_date_column = models.CharField(blank=True, default="", max_length=50, verbose_name="Columna de fecha-renovado")
    additional_column = models.TextField(blank=True, default="", max_length=500, verbose_name="Nombres de columnas adicionales, separados por coma")
    
    user = models.ForeignKey(User, editable=True, verbose_name='Usuario', on_delete=models.CASCADE)
    
    class Meta:
        verbose_name = "Stock"
        verbose_name_plural = "Stocks"
        ordering = ['name']

    def __str__(self):
        return self.name + '-' + str(self.pk)

    def additional_column_as_list(self) -> list:
        """
            Splits the string of additional columns and returns their list.
        """
        return self.additional_column.split(',')

    def extract_products(self):
        """
            Generates the products from the principal file and saves them.
        """
        get_and_save_products(self)

    def set_current_backup(self):
        """
            Set backup based on the current state of the stock and its products.
        """
        backup = Backup(stock = self)
        backup.fill_current()
        backup.save()


pre_save.connect(set_additional_column, sender=Stock)
pre_save.connect(set_default_date_column_name, sender=Stock)
pre_save.connect(unique_name_per_user, sender=Stock)
pre_save.connect(set_compressed_image, sender=Stock)
post_delete.connect(delete_storage_files, sender=Stock)

pre_save.connect(append_residual_files, sender=Stock)
post_save.connect(delete_residual_files, sender=Stock)

pre_delete.connect(delete_backup_files, sender=Stock)

visualstock/stock/forms.py
from django import forms
from django.forms import ModelForm, ValidationError
from .models import Stock

class AddStockStepOne(ModelForm):
    class Meta:
        model = Stock
        fields = ('name', 'image', 'principal_file')
        labels = {
            'name' : 'Nombre de Stock',
            'image' : 'Imagen de Stock',
            'principal_file' : 'Archivo fuente .csv'
        }

    def __init__(self, *args, **kwargs):
        super(AddStockStepOne, self).__init__(*args, **kwargs)

        for field in self.fields:
            self.fields[field].widget.attrs.update({
                'placeholder': self.fields[field].label
            })

        self.fields['name'].widget.attrs.update({
                                                    'autofocus': True,
                                                    'tabindex': 1
                                                })        
        self.fields['principal_file'].widget.attrs.update({
                                                            'accept': '.csv',
                                                            'onchange' :'uploadFilePutName(this)'
                                                          })
        self.fields['image'].widget.attrs.update({'onchange' :'uploadFilePutName(this)'})

    def clean_image(self):
        data = self.cleaned_data['image']

        if data.size >  (10 * (1024**2)): #10 MB
            raise ValidationError(f"La imagen tiene un tamaño mayor al soportado.")

        return data

    def clean_principal_file(self):
        data = self.cleaned_data['principal_file']
        if not data.name.endswith('.csv'):
            self.add_error('principal_file', f"No es un archivo CSV: {data.name}")
        elif data.size >  (5 * (1024**2)): #5 MB
                self.add_error('principal_file', "El archivo CSV tiene un tamaño mayor al soportado.")
        else:
            try:
                data.readline(50).decode('utf-8')
            except:
                self.add_error('principal_file', "El formato de archivo no es un CSV valido.")    
            data.seek(0)

        return data

class AddStockStepTwo(ModelForm):
    class Meta:
        model = Stock
        fields = ('name_column', 'price_column', 'quantity_column')
        labels = {
            'name_column' : 'Columna de nombre-producto',
            'price_column' : 'Columna de precio-producto',
            'quantity_column' : 'Columna de cantidad-productos'
        }

    @staticmethod
    def generate_placeholder(label):
        label = label.replace("Columna de ", "")
        label = label.replace("-", " de ")
        return label.capitalize()


    def __init__(self, *args, **kwargs):
        super(AddStockStepTwo, self).__init__(*args, **kwargs)

        for tabindex, field in enumerate(self.fields, 4):
            self.fields[field].widget.attrs.update({
                'placeholder': self.generate_placeholder(self.fields[field].label),
                'tabindex': 1,
                'list' : 'columnoptions',
            })


    def clean(self):
        cleaned_data = super().clean()
        non_repeating_data = set(cleaned_data.values())

        if len(non_repeating_data) != len(self.fields):
            self.add_error('__all__', 'Los nombres de columnas se repiten entre sí, y esto no es correcto.')
  
class AddStockOptional(ModelForm):
    class Meta:
        model = Stock
        fields = ('category_column', 'added_date_column', 'updated_date_column')
        labels = {
            'category_column' : 'Columna categorias',
            'added_date_column' : 'Columna de fecha-añadido',
            'updated_date_column' : 'Columna de fecha-renovado'
        }

    @staticmethod
    def generate_placeholder(label):
        label = label.replace("Columna de ", "")
        label = label.replace("-", " de ")
        return label.capitalize()

    def __init__(self, *args, **kwargs):
        super(AddStockOptional, self).__init__(*args, **kwargs)

        for tabindex, field in enumerate(self.fields, 7):
            self.fields[field].widget.attrs.update({
                'placeholder': self.generate_placeholder(self.fields[field].label),
                'tabindex': 1,
                'list' : 'columnoptions',
            })

    def clean(self):
        cleaned_data = super().clean()
        non_blank_data = [value for value in cleaned_data.values() if value != ""]
        non_repeating_data = set(non_blank_data)

        if len(non_repeating_data) != len(non_blank_data):
            self.add_error('__all__', 'Los nombres de columnas se repiten entre sí, y esto no es correcto.')

class DeleteStock(forms.Form):
    password = forms.CharField(
                                required=True,
                                label = "Contraseña de Usuario",
                                widget=forms.PasswordInput(
                                    attrs={'type':'password', 'name': 'password','placeholder':'Contraseña de Usuario', 'tabindex' : '1'}
                                    )
                                )

class EditFaceStock(ModelForm):
    name = forms.CharField(
                            required=False,
                            label = "Nombre de Stock",
                            widget = forms.TextInput(
                                attrs = {
                                    'tabindex' : '1',
                                    'placeholder' : 'Nombre de Stock'
                                }))
    image = forms.ImageField(required=False)
    class Meta:
        model = Stock
        fields = ('name', 'image')
        labels = {
            'name' : 'Nombre de Stock',
            'image' : 'Imagen de Stock',
        }

    def __init__(self, *args, **kwargs):
        super(EditFaceStock, self).__init__(*args, **kwargs)

        self.fields['image'].widget.attrs.update({'onchange' :'uploadFilePutNameNoId(this)'})
    
    def clean_image(self):
        data = self.cleaned_data['image']
        if data:
            if data.size >  (10 * (1024**2)): #10 MB
                raise ValidationError(f"La imagen tiene un tamaño mayor al soportado.")

        return data

visualstock/stock/views.py
import json

from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse

from django.contrib.auth.decorators import login_required

from .models import Stock
from products.forms import EditProduct, ImportImages
from django.contrib import messages

from .importProductImages_implement import process_zipfile


# Create your views here.
def stock(request, stock_name):
    """
        Render the stock in template.
    """
    stocks = Stock.objects.filter(user__pk=request.user.pk)
    stock_by_name = get_object_or_404(stocks, name=stock_name)
    products_by_stock = stock_by_name.products.all()

    context = {
        'is_stock': True,
        'stocks' : stocks,
        'stock' : stock_by_name,
        'products' : products_by_stock,
        'mode' : 0
    }

    if request.GET.get("mode"):
        context["mode"] = int(request.GET.get("mode"))

        if context["mode"] == 1:
            context['form_import_images'] = ImportImages()

    return render(request, "stock/stock.html", context)

@login_required
def editProducts(request, stock_name) -> JsonResponse:
    """
        Validate and edit stock products.
    """
    stocks = Stock.objects.filter(user__pk=request.user.pk)
    stock_by_name = get_object_or_404(stocks, name=stock_name)

    if request.method == 'POST' and request.user.username != "Invitados":
        edited_rows = json.loads(request.body)

        for edited_row in edited_rows:
            try:
                product_to_edit = stock_by_name.products.get(id=edited_row["id"])
            except:
                messages.error(request, "Producto no perteneciente a stock")
                return JsonResponse({'error': "Producto no perteneciente a stock"})

            update_request = request.POST.copy()
            update_request.update(edited_row)

            edit_product = EditProduct(update_request)
            if not edit_product.is_valid():
                messages.error(request, "Producto no perteneciente a stock")
                return JsonResponse({'error': "Producto no valido"})
            
            if edited_row.get("name"):
                product_to_edit.name = edited_row["name"]
            if edited_row.get("price") != None:
                product_to_edit.price = edited_row["price"]
            if edited_row.get("quantity") != None:
                product_to_edit.quantity = edited_row["quantity"]
            if edited_row.get("category"):
                product_to_edit.category = edited_row["category"]
            
            product_to_edit.save(update_fields=['name', 'price', 'quantity', 'available', 'category'])
        else:
            if hasattr(stock_by_name, 'backup'):
                stock_by_name.backup.rotate_backup()

        return JsonResponse({'error': None})

@login_required
def importProductImages(request, stock_name):
    """
        Validate and import or update stock products. Process zip files and send multiple images.
    """
    stocks = Stock.objects.filter(user__pk=request.user.pk)
    stock_by_name = get_object_or_404(stocks, name=stock_name)

    if request.method == 'POST' and request.user.username != "Invitados":
        form_import_images = ImportImages(request.POST, request.FILES)
        if form_import_images.is_valid():
            images = {"".join(image.name.split(".")[:-1]):image for image in request.FILES.getlist('images')}
            zip = request.FILES.get('zip')
            if images:
                products_to_add_images = stock_by_name.products.filter(name__in=images.keys())
                for product in products_to_add_images:
                    product.image = images.get(product.name)
                    product.save(update_fields=['image'])
                else:
                    messages.success(request, "Imagenes importadas/actualizadas correctamente")
                    if hasattr(stock_by_name, 'backup'):
                        stock_by_name.backup.rotate_backup()
            if zip:
                process_zipfile(request, stock_by_name, zip)
        else:
            for error_field, error_text in form_import_images.errors.as_data().items():
                messages.error(request, error_text[0].message)

    return redirect("stock:stock", stock_name=stock_name)

@login_required
def deleteProducts(request, stock_name):
    """
        Validate and delete stock products.
    """
    stocks = Stock.objects.filter(user__pk=request.user.pk)
    stock_by_name = get_object_or_404(stocks, name=stock_name)

    if request.method == 'POST' and request.user.username != "Invitados":
        ids_to_remove = json.loads(request.body)
        products_to_remove = stock_by_name.products.filter(pk__in=ids_to_remove)
        try:
            products_to_remove.delete()
        except:
            messages.error(request, "Error al eliminar los productos")
            return JsonResponse({'error': "Error al eliminar los productos"})
        finally:
            if hasattr(stock_by_name, 'backup'):
                stock_by_name.backup.rotate_backup()
        
        return JsonResponse({'error': None})

visualstock/stock/templates/stock/stock.html
{% extends 'layouts/layout.html' %}
{% load static %}

{% block title %}
    {{ stock.name | capfirst }}
{% endblock title %}

{% block content %}

    {% if mode == 0 %}
        <button onclick="document.querySelector('.filter--modal').showModal()" class="filter--button" title="Filtrar productos" tabindex="1">
            <span class="icon-mug"></span>&nbsp;Filtrar productos
        </button>
    {% endif %}


    {% if mode == 1 %}
        {% if request.user.username == "Invitados" %}
            <div class="edit-button_box">
                <button onclick="window.alert('Opción inhabilitada para invitados. Registrese para probar.')" class="import-img--button" title="Importar/Actualizar imagenes" tabindex="1">
                    <span class="principal--text">Importar/Actualizar imagenes</span>
                    <span class="auxiliar--icon icon-images"></span>
                </button>
                <button onclick="window.alert('Opción inhabilitada para invitados. Registrese para probar.')" class="edit--button" title="Guardar edición" tabindex="1">
                    <span class="principal--text">Guardar cambios</span>
                    <span class="auxiliar--icon icon-pencil2"></span>
                </button>
            </div>
        {% else %}
            <div class="edit-button_box">
                <button onclick="showDialogImportImages()" class="import-img--button" title="Importar/Actualizar imagenes" tabindex="1">
                    <span class="principal--text">Importar/Actualizar imagenes</span>
                    <span class="auxiliar--icon icon-images"></span>
                </button>
                <button onclick="saveItems()" class="edit--button" title="Guardar edición" tabindex="1">
                    <span class="principal--text">Guardar cambios</span>
                    <span class="auxiliar--icon icon-pencil2"></span>
                </button>
            </div>
        {% endif %}
    {% endif %}

    {% if mode == 2 %}
        {% if request.user.username == "Invitados" %}
            <button onclick="window.alert('Opción inhabilitada para invitados. Registrese para probar.')" class="delete--button" title="Guardar edición" tabindex="1">
                Eliminar&nbsp;<span class="delete--counter">0</span>&nbsp;productos
            </button>
        {% else %}
            <button onclick="deleteItems()" class="delete--button" title="Guardar edición" tabindex="1">
                Eliminar&nbsp;<span class="delete--counter">0</span>&nbsp;productos
            </button>
        {% endif %}
    {% endif %}

    <div class="content-table">
        <table>
            <thead>
                <tr>
                    {% if mode == 2 %}
                        <th>ELIMINAR</th>
                    {% endif %}
                    <th>Imagen</th>
                    <th>{{ stock.name_column }}</th>
                    <th>{{ stock.price_column }}</th>
                    <th>{{ stock.quantity_column }}</th>
                    <th>Disponible</th>
                    {% if stock.category_column %}
                        <th>{{ stock.category_column }}</th>
                    {% endif %}
                    <th>{{ stock.added_date_column }}</th>
                    <th>{{ stock.updated_date_column }}</th>
                    {% if stock.additional_column %}
                        {% for additional_column_name in stock.additional_column_as_list %}
                            <th>{{ additional_column_name }}</th>
                        {% endfor %}
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for product in products %}
                    <tr>
                        {% if mode == 1 %}
                            <input type="hidden" value="{{ product.pk }}">
                        {% endif %}
                        {% if mode == 2 %}
                                <td class="product--check-delete">
                                    <label for="item-{{ product.pk }}">
                                        <input type="checkbox" id="item-{{ product.pk }}" class="delete--item">
                                    </label>
                                </td>
                        {% endif %}
                        <td class="product--img">
                            {% if product.image %}
                                <img width="400px" src="{{ product.image.url }}" alt="{{ product.name }}">
                            {% endif %}
                        </td>
                        <td class="product--name" {% if mode == 1 %}contenteditable{% endif %}>{{ product.name }}</td>
                        <td class="product--price" {% if mode == 1 %}contenteditable{% endif %}>{{ product.price | floatformat:2 }}</td>
                        <td class="product--quantity" {% if mode == 1 %}contenteditable{% endif %}>{{ product.quantity }}</td>
                        <td class="{{ product.available | yesno:'available,noavailable' }} product--available">
                            {{ product.available | yesno:"✓,X" }}
                        </td>
                        {% if stock.category_column %}
                            <td class="product--category" {% if mode == 1 %}contenteditable{% endif %}>{{ product.category }}</td>
                        {% endif %}
                        <td>{{ product.added_date }}</td>
                        <td>{{ product.updated_date }}</td>
                        {% if stock.additional_column %}
                            {% for additional_value in product.additional_as_list %}
                                <td>{{ additional_value | default:"-" }}</td>
                            {% endfor %}
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    {% if request.user.username != "Invitados" %}
        <dialog class="d--modal">
            <section class="plain_panel">
                <h2 class="section__title">Importar/Actualizar Imagenes</h2>
                <section class="section__description" tabindex="1">
                    <p>Para importar o actualizar imagenes, sus imagenes deben tener <strong>el mismo nombre que el producto.</strong></p>
                    <p>Se dispone de dos opciones, cargar un archivo zip con las imagenes ó cargar las imagenes directamente.</p>
                    <p>Las imagenes con nombres incorrectos seran ignoradas.</p>
                    <div class="button--container">
                        <button onclick="uploadZip()" class="upload__import">
                            <span class='icon-file-zip'></span>
                            &nbsp;Importar Zip
                        </button>
                        <button onclick="uploadImages()" class="upload__import">
                            <span class='icon-images'></span>
                            &nbsp;Importar Imagenes
                        </button>
                        <button class="close__dialog">Cerrar</button>
                    </div>
                </section>
            </section>
            <form id="form--import_images" action="{% url 'stock:importProductImages' stock.name %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% for field in form_import_images %}
                {{ field }}
                {% endfor %}
            </form>
        </dialog>
        {% endif %}
        
        {% if mode == 0 %}
        <dialog class="d--modal filter--modal">
            <section class="plain_panel">
                <button id="filter_close--button" onclick="document.querySelector('.filter--modal').close()">Cerrar</button>
                <h2 class="section__title">Filtrar Productos</h2>
                <section class="section__description" tabindex="1">
                    <p>Los productos filtrados son solo para visualización.</p>
                    <p>Al actualizar la pagina se visualizaran todos los productos como es usual.</p>
                    <p>Se pueden usar uno o más filtros.</p>
                    <form class="form--filter">
                        <fieldset id="filter--by--name">
                            <legend>Por Nombre:</legend>
                            <input type="checkbox" id="apply--name_filter">
                            <input type="text" list="product__names" name="product__name" id="product__name" disabled>
                            <datalist id="product__names">
                            </datalist>
                        </fieldset>

                        {% if stock.category_column %}
                            <fieldset id="filter--by--category">
                                <legend>Por Categoria:</legend>
                                <input type="checkbox" id="apply--category_filter">
                                <input type="text" list="product__categories" name="product__category" id="product__category" disabled>
                                <datalist id="product__categories">
                                </datalist>
                            </fieldset>                        
                        {% endif %}

                        <fieldset id="filter--by--price">
                            <legend>Por Precio:</legend>
                            <input type="checkbox" id="apply--price_filter">
                            <span class="subtitle--fieldset">Min: </span>
                            <span class="price__range--min_value">Indefinido</span>
                            <input disabled type="range" name="price__range--min" id="price__range--min" step="0.01">
                            <span class="subtitle--fieldset">Max: </span>
                            <span class="price__range--max_value">Indefinido</span>
                            <input disabled type="range" name="price__range--max" id="price__range--max" step="0.01">
                        </fieldset>

                        <fieldset id="filter--by--quantity">
                            <legend>Por Cantidad:</legend>
                            <input type="checkbox" id="apply--quantity_filter">
                            <span class="subtitle--fieldset">Min: </span>
                            <span class="quantity__range--min_value">Indefinido</span>
                            <input disabled type="range" name="quantity__range--min" id="quantity__range--min" step="1">
                            <span class="subtitle--fieldset">Max: </span>
                            <span class="quantity__range--max_value">Indefinido</span>
                            <input disabled type="range" name="quantity__range--max" id="quantity__range--max" step="1">
                        </fieldset>
                    </form>
                    <button id="filter_end--button" onclick="applyFilter()">Filtrar</button>
                </section>
            </section>
        </dialog>
    {% endif %}

{% endblock content %}

{% block scripts %}
    {% if request.user.is_authenticated %}
        {% if mode == 0 %}
            <script src="{% static 'js/filter-interactive.js' %}" async></script>
        {% endif %}
        {% if mode == 1 %}
            <script>const url_edit_products = "{% url 'stock:editProducts' stock.name %}";</script>
            <script src="{% static 'js/editTableStock.js' %}" async></script>
            <script src="{% static 'js/importImages.js' %}" async></script>
        {% endif %}
        {% if mode == 2 %}
            <script>const url_delete_products = "{% url 'stock:deleteProducts' stock.name %}";</script>
            <script src="{% static 'js/deleteItemTableStock.js' %}" async></script>
        {% endif %}
    {% endif %}
{% endblock scripts %}